#ifndef _CANFESTIVAL_EXAMPLES_KERNELTEST_CONSOLE_CONSOLE_H
#define _CANFESTIVAL_EXAMPLES_KERNELTEST_CONSOLE_CONSOLE_H

#define DEVICE_NAME "canf_ktest"

#define CMD_START	'1'
#define CMD_STOP	'2'

#endif // _CANFESTIVAL_EXAMPLES_KERNELTEST_CONSOLE_CONSOLE_H
