
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef _CANFESTIVAL_EXAMPLES_WIN32TEST_WIN32TEST_H
#define _CANFESTIVAL_EXAMPLES_WIN32TEST_WIN32TEST_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 win32test_valueRangeTest (UNS8 typeValue, void * value);
const indextable * win32test_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data win32test_Data;

#endif // _CANFESTIVAL_EXAMPLES_WIN32TEST_WIN32TEST_H
